# Common geometry and math utils.

package(
    default_visibility = ["//visibility:public"],
)

cc_library(
   name = "primitive_types_2d",
   srcs = ["primitive_types_2d.cc"],
   hdrs = ["primitive_types_2d.h"],
   deps = [
      "@com_google_absl//absl/log:check",
      "@com_google_absl//absl/log:log",
      "@com_google_absl//absl/strings",
   ],
)