load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

http_archive(
  name = "com_google_absl",
  urls = ["https://github.com/abseil/abseil-cpp/archive/master.zip"],      
  strip_prefix = "abseil-cpp-master",
)

http_archive(
  name = "bazel_skylib",
  urls = ["https://github.com/bazelbuild/bazel-skylib/releases/download/1.2.1/bazel-skylib-1.2.1.tar.gz"],
  sha256 = "f7be3474d42aae265405a592bb7da8e171919d74c16f082a5457840f06054728",
)

http_archive(
    name = "com_google_googletest",  # 2022-06-16T20:18:32Z
    sha256 = "a1d3123179024258f9c399d45da3e0b09c4aaf8d2c041466ce5b4793a8929f23",
    strip_prefix = "googletest-86add13493e5c881d7e4ba77fb91c1f57752b3a4",
    # Keep this URL in sync with ABSL_GOOGLETEST_COMMIT in ci/cmake_common.sh.
    urls = ["https://github.com/google/googletest/archive/86add13493e5c881d7e4ba77fb91c1f57752b3a4.zip"],
)

# Google benchmark.
http_archive(
    name = "com_github_google_benchmark",  # 2021-09-20T09:19:51Z
    sha256 = "62e2f2e6d8a744d67e4bbc212fcfd06647080de4253c97ad5c6749e09faf2cb0",
    strip_prefix = "benchmark-0baacde3618ca617da95375e0af13ce1baadea47",
    urls = ["https://github.com/google/benchmark/archive/0baacde3618ca617da95375e0af13ce1baadea47.zip"],
)

# http_archive(
#     name = "rapidjson",
#     urls = [
#         #"https://github.com/Tencent/rapidjson/archive/v1.1.0.tar.gz",
#         "https://github.com/Tencent/rapidjson/archive/refs/tags/v1.1.0.zip",
#     ],
#     sha256 = "bf7ced29704a1e696fbccf2a2b4ea068e7774fa37f6d7dd4039d0787f8bed98e",
#     strip_prefix = "rapidjson-1.1.0",
#     build_file = "//third_party/rapidjson/BUILD",
# )


http_archive(
    name = "rapidjson",
    url = "https://github.com/Tencent/rapidjson/archive/v1.1.0.zip",
    sha256 = "8e00c38829d6785a2dfb951bb87c6974fa07dfe488aa5b25deec4b8bc0f6a3ab",
    strip_prefix = "rapidjson-1.1.0",
    build_file = "@//third_party/rapidjson:BUILD",
)

http_archive(
    name = "cpp_httplib",
    url = "https://github.com/yhirose/cpp-httplib/archive/v0.11.3.zip",
    sha256 = "d1f4df73a7e39ccceeda08b3e0bd407497d76eabf30fc892ffa6978b2b893a05",
    strip_prefix = "cpp-httplib-0.11.3",
    build_file = "@//third_party/cpp_httplib:BUILD",
)